name: CI ðŸ§ª

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: [main, develop] }

jobs:
  ###############################
  #             Test            #
  ###############################
  test:
    name: ${{ matrix.testMode }} âœ¨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
        unityVersion:
          - 2020.3.22f1
    steps:

      # This destroys 2GB free quota within a day
      #      - uses: actions/checkout@v2
      #        with:
      #          lfs: true

      # Workaround: https://github.com/actions/checkout/issues/165#issuecomment-657673315
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Restore Library cache
        uses: actions/cache@v2
        id: lib-cache
        with:
          path: Library
          key: Library-Test
          restore-keys: |
            Library-
      - name: Test run
        uses: game-ci/unity-test-runner@v2.0-alpha-5
        id: testRunner
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
          unityVersion: ${{ matrix.unityVersion }}
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test results (${{ matrix.testMode }})
          path: ${{ steps.testRunner.outputs.artifactsPath }}